### ISSUE TITLE
Architecture de fichiers

### ISSUE THREAD

**Issue by FauconFan** [xavitator/Triforce_HC_2019#4]
Je vois bien une architecture comme ça:
/
/graphes
/--/Dijkstra
/--/--/C++
/--/--/Java
/--/--/Python
/--/Kruskal
/--/--/...
/numbers

etc.

Ça vous va ?

**Comment by FauconFan** [comment]
C'est mieux peut-être par langage je sais pas...

**Comment by xavitator** [comment]
Hum... Par langage ce sera plus simple, comme ça si on cherche qqch, on sait qu'on va être dans un certain langage avant tout ^^
Et au niveau des imports/includes/open, ce sera plus simple.
Et comme ça, un makefile par langage ^^

**Comment by FauconFan** [comment]
Ca me va
