### ISSUE TITLE
Graphe Structure Java

### ISSUE THREAD

**Issue by maiste** [xavitator/Triforce_HC_2019#8]
Je suis pas convaincu de la manière de produire des graphes en Java... ça fait des algos pas très modulable pour la HashCode et difficilement copiable... Pour moi tant qu'on a le temps, il faut faire des codes très modulables et surtout facile à copier...

**Comment by maiste** [comment]
cf commit  6ce1695

**Comment by xavitator** [comment]
tu penses à quoi d'autres comme structure ? tu veux qu'on donne uniquement ce qui est interessant au programme ?
Et donc on n'a pas de structure de graphe ? On la créera le moment venu ?

**Comment by xavitator** [comment]
On va faire ca.
Petit commentaire pour expliquer vite fait les arguments : ex commit cf371a61fa52d34f874e55c11adae23d059f8757

**Comment by maiste** [comment]
Désolé pour les commentaires le but était de faire une proposition de structure : je fais attention sur les prochains commits.
